"""added oauth provider id in user

Revision ID: 446d4fffcf13
Revises: 711387f50347
Create Date: 2022-08-23 19:26:13.500911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446d4fffcf13'
down_revision = '711387f50347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_provider_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['oauth_provider_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'oauth_provider_id')
    # ### end Alembic commands ###
