"""renamed column of oauth in user table

Revision ID: 629bdee760a6
Revises: 446d4fffcf13
Create Date: 2022-08-23 19:31:41.483471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629bdee760a6'
down_revision = '446d4fffcf13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_account_id', sa.String(), nullable=True))
    op.drop_constraint('user_oauth_provider_id_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['oauth_account_id'])
    op.drop_column('user', 'oauth_provider_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('oauth_provider_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_oauth_provider_id_key', 'user', ['oauth_provider_id'])
    op.drop_column('user', 'oauth_account_id')
    # ### end Alembic commands ###
