"""email is nullable

Revision ID: 711387f50347
Revises: 61b4e9c919b0
Create Date: 2022-08-23 19:08:07.136963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711387f50347'
down_revision = '61b4e9c919b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
