"""Added completion and due date in task model

Revision ID: 7f7ec1851f1a
Revises: 31bf6cc8845d
Create Date: 2022-08-26 12:42:48.231956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7ec1851f1a'
down_revision = '31bf6cc8845d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'created_at')
    op.drop_column('task', 'completed')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
