"""Added TaskList and self relation on Task

Revision ID: bc224ec447a6
Revises: eddd118237ba
Create Date: 2022-08-18 17:09:22.851351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc224ec447a6'
down_revision = 'eddd118237ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('title', sa.String(), nullable=False))
    op.add_column('task', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task_list', ['list_id'], ['id'])
    op.create_foreign_key(None, 'task', 'task', ['parent_id'], ['id'])
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'list_id')
    op.drop_column('task', 'parent_id')
    op.drop_column('task', 'title')
    op.drop_table('task_list')
    # ### end Alembic commands ###
